# Generated by Django 6.0.3 on 2026-03-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Entidade (Model)')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Sistema')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('caminho_geracao', models.CharField(blank=True, max_length=255, verbose_name='Pasta onde gerar o projeto')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Campo')),
                ('tipo', models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField'), ('IntegerField', 'IntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField')], max_length=20, verbose_name='Tipo do Campo')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Length (Char/Text)')),
                ('decimal_places', models.PositiveIntegerField(blank=True, null=True, verbose_name='Casas Decimais')),
                ('max_digits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dígitos Totais')),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('verbose_name', models.CharField(blank=True, max_length=100)),
                ('help_text', models.TextField(blank=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='sistema.entidade')),
                ('entidade_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_relacionados', to='sistema.entidade', verbose_name='Entidade Relacionada')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['entidade', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='entidade',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='sistema.modulo'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='sistema.sistema'),
        ),
        migrations.AlterUniqueTogether(
            name='entidade',
            unique_together={('modulo', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('sistema', 'nome')},
        ),
    ]
