# Generated by Django 6.0.3 on 2026-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='default_value',
            field=models.CharField(blank=True, help_text="Valor padrão (ex: 'Ativo', True, 0)", max_length=255),
        ),
        migrations.AddField(
            model_name='campo',
            name='on_delete',
            field=models.CharField(blank=True, choices=[('models.CASCADE', 'CASCADE'), ('models.PROTECT', 'PROTECT'), ('models.SET_NULL', 'SET_NULL'), ('models.RESTRICT', 'RESTRICT')], default='models.CASCADE', max_length=50),
        ),
        migrations.AddField(
            model_name='campo',
            name='related_name_str',
            field=models.CharField(blank=True, max_length=100, verbose_name='Related Name'),
        ),
        migrations.AddField(
            model_name='campo',
            name='upload_to',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pasta de Upload (File/Image)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='gerar_admin',
            field=models.BooleanField(default=True, verbose_name='Registrar no admin.py?'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='gerar_crud_views',
            field=models.BooleanField(default=False, verbose_name='Gerar Views e Templates de CRUD?'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='gerar_endpoints_api',
            field=models.BooleanField(default=False, verbose_name='Gerar ViewSets e Serializers (API)?'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='nome_plural',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome no Plural (Verbose Name Plural)'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='banco_dados',
            field=models.CharField(choices=[('sqlite3', 'SQLite'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle')], default='sqlite3', max_length=50, verbose_name='Banco de dados'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='gerar_api_rest',
            field=models.BooleanField(default=False, verbose_name='Configurar Django Rest Framework?'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='gerar_docker',
            field=models.BooleanField(default=False, verbose_name='Gerar Dockerfile e docker-compose?'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='usar_custom_user',
            field=models.BooleanField(default=True, verbose_name='Gerar Custom User Model?'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='decimal_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Casas Decimais (Decimal)'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='max_digits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dígitos Totais (Decimal)'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Length'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'CharField'), ('TextField', 'TextField'), ('IntegerField', 'IntegerField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('FileField', 'FileField'), ('ImageField', 'ImageField'), ('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('OneToOneField', 'OneToOneField')], max_length=20, verbose_name='Tipo do Campo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Módulo (App)'),
        ),
    ]
