# Generated by Django 6.0.3 on 2026-03-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_campo_default_value_campo_on_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='tipo_menu',
            field=models.CharField(choices=[('lateral', 'Menu Lateral (Sidebar)'), ('superior', 'Menu Superior (Navbar)')], default='lateral', max_length=20, verbose_name='Estilo do Menu'),
        ),
    ]
