# Generated by Django 6.0.3 on 2026-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_sistema_tipo_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='usar_auditoria',
            field=models.BooleanField(default=False, verbose_name='Usar Auditoria?'),
        ),
    ]
