# Generated by Django 6.0.3 on 2026-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_sistema_usar_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='arquivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='sistemas_zip/'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
