# Generated by Django 6.0.3 on 2026-07-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_sistema_arquivo_zip_sistema_atualizado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
