# Generated by Django 6.1 on 2026-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0007_gen0001_estabilizacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campo",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="Valor padrão literal (ex: Ativo, True, 0)",
                max_length=255,
            ),
        ),
    ]
