# Generated by Django 6.1 on 2026-09-03 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_deployment_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('SYSTEM', 'Sistema'), ('GENERATION', 'Geração'), ('VALIDATION', 'Validação'), ('RELEASE', 'Release'), ('DEPLOYMENT', 'Deployment'), ('RUNTIME', 'Runtime'), ('SECURITY', 'Segurança'), ('INTEGRATION', 'Integração')], default='SYSTEM', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('event_name', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to='sistema.ambiente')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observability_events', to='sistema.sistema')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Observabilidade',
                'verbose_name_plural': 'Eventos de Observabilidade',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sistema', 'created_at'], name='obs_system_created_idx'), models.Index(fields=['sistema', 'level', 'created_at'], name='obs_system_level_idx'), models.Index(fields=['ambiente', 'created_at'], name='obs_env_created_idx'), models.Index(fields=['category', 'created_at'], name='obs_category_created_idx'), models.Index(fields=['event_name', 'created_at'], name='obs_event_created_idx')],
            },
        ),
    ]
